In [17]:
import numpy as np
import pandas as pd

from statsbombpy import sb
from tqdm import tqdm

In [18]:
competitions = sb.competitions()
competitions.head()

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-07-06T04:26:07.636270,2025-07-06T04:26:07.636270,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-09-28T01:57:35.846538,None,None,2024-09-28T01:57:35.846538
3,16,4,Europe,Champions League,male,False,False,2018/2019,2025-05-08T15:10:50.835274,2021-06-13T16:17:31.694,None,2025-05-08T15:10:50.835274
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882

In [19]:
competitions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   competition_id             75 non-null     int64
 1   season_id                  75 non-null     int64
 2   country_name               75 non-null     object
 3   competition_name           75 non-null     object
 4   competition_gender         75 non-null     object
 5   competition_youth          75 non-null     bool
 6   competition_international  75 non-null     bool
 7   season_name                75 non-null     object
 8   match_updated              75 non-null     object
 9   match_updated_360          57 non-null     object
 10  match_available_360        11 non-null     object
 11  match_available            75 non-null     object
dtypes: bool(2), int64(2), object(8)
memory usage: 6.1+ KB

In [20]:
competitions[
    [
        "competition_name",
        "season_name",
        "country_name",
        "competition_gender"
    ]
].drop_duplicates().sort_values(
    by=["competition_name", "season_name"]
)

          competition_name season_name   country_name competition_gender
1            1. Bundesliga   2015/2016        Germany               male
0            1. Bundesliga   2023/2024        Germany               male
2   African Cup of Nations        2023         Africa               male
20        Champions League   1970/1971         Europe               male
19        Champions League   1971/1972         Europe               male
..                     ...         ...            ...                ...
70      UEFA Europa League   1988/1989         Europe               male
72       UEFA Women's Euro        2022         Europe             female
71       UEFA Women's Euro        2025         Europe             female
74       Women's World Cup        2019  International             female
73       Women's World Cup        2023  International             female

[75 rows x 4 columns]

In [21]:
international_comps = competitions[
    (competitions['competition_gender'] == 'male') &
    (competitions['competition_international'] == True)
]

international_comps[
    [
        'competition_id',
        'season_id',
        'competition_name',
        'season_name'
    ]
].sort_values(
    by = ['competition_name','season_name']
)

    competition_id  season_id        competition_name season_name
2             1267        107  African Cup of Nations        2023
21             223        282            Copa America        2024
28            1470        274      FIFA U20 World Cup        1979
36              43        269          FIFA World Cup        1958
35              43        270          FIFA World Cup        1962
34              43        272          FIFA World Cup        1970
33              43         51          FIFA World Cup        1974
32              43         54          FIFA World Cup        1986
31              43         55          FIFA World Cup        1990
30              43          3          FIFA World Cup        2018
29              43        106          FIFA World Cup        2022
69              55         43               UEFA Euro        2020
68              55        282               UEFA Euro        2024

In [22]:
international_comps[
    [
        'competition_name',
        'season_name'
    ]
]

          competition_name season_name
2   African Cup of Nations        2023
21            Copa America        2024
28      FIFA U20 World Cup        1979
29          FIFA World Cup        2022
30          FIFA World Cup        2018
31          FIFA World Cup        1990
32          FIFA World Cup        1986
33          FIFA World Cup        1974
34          FIFA World Cup        1970
35          FIFA World Cup        1962
36          FIFA World Cup        1958
68               UEFA Euro        2024
69               UEFA Euro        2020

In [23]:
selected_comps = international_comps[
    (
        (
            international_comps['competition_name'] == "FIFA World Cup"
        ) &
        (
            international_comps['season_name'].isin(['2018','2022'])
        ) 
    ) |
    (
        (
            international_comps['competition_name'] == "UEFA Euro"
        )&
        (
            international_comps['season_name'].isin(['2020','2024'])
        )
    ) |
    (
        international_comps['competition_name'] == "Copa America"
    ) |
    (
        international_comps['competition_name'] == "African Cup of Nations"
    )
]

selected_comps[
    [
        'competition_name',
        'season_name'
    ]
]

          competition_name season_name
2   African Cup of Nations        2023
21            Copa America        2024
29          FIFA World Cup        2022
30          FIFA World Cup        2018
68               UEFA Euro        2024
69               UEFA Euro        2020

In [24]:
all_matches=[]
for _,row in selected_comps.iterrows():

    comp_id = row['competition_id']
    season_id = row['season_id']

    print(f'Fetching matches for {row['competition_name']} {row['season_name']}')

    matches = sb.matches(
        competition_id = comp_id,
        season_id = season_id
    )

    matches['competition_name'] = row['competition_name']
    matches['season_name'] = row['season_name']

    all_matches.append(matches)

matches_df = pd.concat(all_matches,ignore_index = True)
print(matches_df.shape)

matches_df.head()

Fetching matches for African Cup of Nations 2023

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching matches for Copa America 2024

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching matches for FIFA World Cup 2022

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching matches for FIFA World Cup 2018

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching matches for UEFA Euro 2024

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching matches for UEFA Euro 2020

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

(314, 56)

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version,season_name
0,3923881,2024-02-11,22:00:00.000,1,2,available,unscheduled,2024-02-13T20:09:29.909933,None,8,...,1868.0,Emerse Faé,None,1984-01-24,55.0,Côte d'Ivoire,1.1.0,2,2,2023
1,3923880,2024-02-10,22:00:00.000,0,0,available,unscheduled,2024-02-13T18:33:05.612366,None,7,...,5011.0,Sébastien Desabre,None,1976-08-02,78.0,France,1.1.0,2,2,2023
2,3922838,2024-02-07,22:00:00.000,1,0,available,unscheduled,2024-02-13T15:29:15.994740,None,6,...,5011.0,Sébastien Desabre,None,1976-08-02,78.0,France,1.1.0,2,2,2023
3,3922837,2024-02-07,19:00:00.000,1,1,available,unscheduled,2024-02-14T02:17:51.833305,None,6,...,1801.0,Hugo Henri Broos,None,1952-04-10,22.0,Belgium,1.1.0,2,2,2023
4,3922242,2024-01-29,22:00:00.000,1,1,available,unscheduled,2024-02-01T19:27:17.255105,None,4,...,1868.0,Emerse Faé,None,1984-01-24,55.0,Côte d'Ivoire,1.1.0,2,2,2023

In [25]:
matches_df[
    [
        'match_id',
        'home_team',
        'away_team',
        'competition_name',
        'season_name'
    ]
].head()

   match_id      home_team      away_team        competition_name season_name
0   3923881        Nigeria  Côte d'Ivoire  African Cup of Nations        2023
1   3923880   South Africa       Congo DR  African Cup of Nations        2023
2   3922838  Côte d'Ivoire       Congo DR  African Cup of Nations        2023
3   3922837        Nigeria   South Africa  African Cup of Nations        2023
4   3922242        Senegal  Côte d'Ivoire  African Cup of Nations        2023

In [26]:
all_shots=[]

for _,match in matches_df.iterrows():
    match_id = match['match_id']

    try:
        print(f'Fetching events for match {match_id}')

        events = sb.events(match_id = match_id)
        #shots only
        shots = events[
            events['type'] == 'Shot'
        ].copy()

        #add metadata
        shots['competition_name'] = match['competition_name']
        shots['season_name']= match['season_name']
        shots['match_id']=match_id

        all_shots.append(shots)

    except Exception as e:
        print(f'Error in match{match_id}:{e}')

shots_df = pd.concat(
    all_shots,
    ignore_index=True
)   

print(shots_df.shape)

shots_df.head()

Fetching events for match 3923881

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3923880

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3922838

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3922837

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3922242

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3922239

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3922659

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3922658

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3922244

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3922356

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3922321

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3922237

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3922243

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3922241

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3922240

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3922238

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920396

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920386

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920385

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920387

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920419

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920418

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920417

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920416

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920415

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920414

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920413

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920412

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920411

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920410

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920409

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920408

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920407

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920406

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920405

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920404

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920403

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920402

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920401

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920400

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920399

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920398

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920397

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920395

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920394

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920393

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920392

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920391

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920390

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920389

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920388

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3920384

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3943077

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3943076

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3942852

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3942785

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3942416

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3942415

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939986

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939973

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3942229

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3942228

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939985

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939984

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939981

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939992

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939991

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939990

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939989

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939988

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939987

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939983

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939982

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939980

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939979

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939978

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939977

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939976

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939975

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939974

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939972

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939971

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939970

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3939969

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857256

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3869151

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857257

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857258

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857288

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857267

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3869321

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857287

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3869486

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3869685

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857260

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857264

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857266

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857289

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857269

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857294

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3869254

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3869118

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3869684

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3869519

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3869354

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3869552

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3869420

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3869220

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3869219

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3869253

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3869152

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3869117

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857270

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857263

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857259

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857295

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857283

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857284

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857282

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857286

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857301

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857300

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857299

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857298

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857297

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857296

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857293

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857292

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857291

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857290

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857285

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857281

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857280

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857279

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857278

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857277

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857276

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857275

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857274

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857273

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857272

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857271

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857268

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857265

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857262

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857261

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857255

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3857254

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7585

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7570

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7586

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7557

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7542

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 8656

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7554

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7550

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7548

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7578

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7553

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7544

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7536

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7555

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7546

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7539

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7538

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7576

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7565

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7551

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7537

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7580

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 8650

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7581

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7549

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7529

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7534

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7562

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7571

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7569

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7568

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7530

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7558

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7583

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7547

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7535

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7584

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7545

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 8649

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 8658

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7561

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7531

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7582

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7552

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7532

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7560

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7533

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7564

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7579

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7572

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7577

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7543

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7525

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7566

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 8651

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7567

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7541

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 8655

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 8657

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7540

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 8652

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7563

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7556

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 7559

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3942819

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3943043

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3942752

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3942382

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3942349

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930180

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930171

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3942227

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3942226

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3938645

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930184

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3941022

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3941021

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3941020

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3941019

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3941018

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3941017

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930182

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930179

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3940983

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3940878

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930177

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930173

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930172

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930167

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930168

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930165

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930164

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930161

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3938637

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3938640

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3938642

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3938639

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3938641

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3938644

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3938643

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3938638

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930183

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930181

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930178

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930176

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930175

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930174

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930170

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930169

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930166

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930163

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930162

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930160

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930159

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3930158

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3795108

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788769

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788766

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3795220

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788761

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788764

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788773

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788755

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788754

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788762

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788760

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788747

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788741

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3795109

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3795187

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788770

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3795506

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3794688

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3794692

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3794686

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3794687

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3794685

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788774

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788771

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788772

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788768

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788767

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788753

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788765

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788763

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788759

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788758

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788757

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788745

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3795107

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3795221

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3794689

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788746

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3794691

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3794690

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788756

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788749

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788750

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788748

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788751

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788752

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788742

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788775

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788776

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788743

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Fetching events for match 3788744

C:\Users\joshi\anaconda3\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

(7863, 119)

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,...,goalkeeper_shot_saved_off_target,shot_saved_off_target,player_off_permanent,block_save_block,goalkeeper_lost_in_play,goalkeeper_penalty_saved_to_post,shot_follows_dribble,half_start_late_video_start,goalkeeper_success_in_play,pass_backheel
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
shots_df.to_csv(
    "../data/raw/international_shots.csv",
    index=False
)

print("Dataset saved successfully")

Dataset saved successfully