In [12]:
import pandas as pd
df = pd.read_csv("../data/raw/international_shots.csv")

df.head()

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,...,goalkeeper_shot_saved_off_target,shot_saved_off_target,player_off_permanent,block_save_block,goalkeeper_lost_in_play,goalkeeper_penalty_saved_to_post,shot_follows_dribble,half_start_late_video_start,goalkeeper_success_in_play,pass_backheel
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7863 entries, 0 to 7862
Columns: 119 entries, 50_50 to pass_backheel
dtypes: float64(80), int64(9), object(30)
memory usage: 7.1+ MB

In [14]:
important_columns = [
    "match_id",
    "competition_name",
    "season_name",
    "minute",
    "second",
    "period",
    "team",
    "player",
    "position",
    "location",
    "shot_end_location",
    "shot_body_part",
    "shot_technique",
    "play_pattern",
    "under_pressure",
    "shot_first_time",
    "shot_one_on_one",
    "shot_open_goal",
    "shot_deflected",
    "shot_statsbomb_xg",
    "shot_outcome"
]

shots_clean = df[important_columns].copy()

print(shots_clean.shape)

shots_clean.head()

(7863, 21)

,match_id,competition_name,season_name,minute,second,period,team,player,position,location,...,shot_body_part,shot_technique,play_pattern,under_pressure,shot_first_time,shot_one_on_one,shot_open_goal,shot_deflected,shot_statsbomb_xg,shot_outcome
0,3923881,African Cup of Nations,2023,3,36,1,Côte d'Ivoire,Sébastien Haller,Center Forward,"[106.7, 42.1]",...,Head,Normal,From Free Kick,True,NaN,NaN,NaN,NaN,0.077357,Wayward
1,3923881,African Cup of Nations,2023,6,10,1,Côte d'Ivoire,Sébastien Haller,Center Forward,"[109.1, 35.5]",...,Right Foot,Half Volley,From Corner,NaN,True,NaN,NaN,NaN,0.187051,Off T
2,3923881,African Cup of Nations,2023,7,8,1,Côte d'Ivoire,Simon Adingra,Left Wing,"[113.6, 23.8]",...,Right Foot,Half Volley,Regular Play,NaN,NaN,NaN,NaN,NaN,0.013922,Off T
3,3923881,African Cup of Nations,2023,13,4,1,Côte d'Ivoire,Seko Fofana,Left Center Midfield,"[91.8, 40.2]",...,Right Foot,Normal,From Corner,NaN,NaN,NaN,NaN,NaN,0.027030,Saved
4,3923881,African Cup of Nations,2023,20,1,1,Côte d'Ivoire,Obite Evan Ndicka,Left Center Back,"[111.0, 31.3]",...,Head,Normal,From Corner,NaN,NaN,NaN,NaN,NaN,0.030268,Wayward

In [15]:
shots_clean.isnull().sum()

match_id                0
competition_name        0
season_name             0
minute                  0
second                  0
period                  0
team                    0
player                  0
position                0
location                0
shot_end_location       0
shot_body_part          0
shot_technique          0
play_pattern            0
under_pressure       6013
shot_first_time      5711
shot_one_on_one      7489
shot_open_goal       7795
shot_deflected       7740
shot_statsbomb_xg       0
shot_outcome            0
dtype: int64

In [20]:
shots_clean["x"] = shots_clean["location"].apply(
    lambda loc: loc[0] if isinstance(loc, list) else None
)

shots_clean["y"] = shots_clean["location"].apply(
    lambda loc: loc[1] if isinstance(loc, list) else None
)

shots_clean["end_x"] = shots_clean["shot_end_location"].apply(
    lambda loc: loc[0] if isinstance(loc, list) else None
)

shots_clean["end_y"] = shots_clean["shot_end_location"].apply(
    lambda loc: loc[1] if isinstance(loc, list) else None
)

In [21]:
shots_clean['goal'] = shots_clean['shot_outcome'].apply(
    lambda x:1 if x == 'Goal' else 0
)

In [22]:
shots_clean['goal'].value_counts()

goal
0    6950
1     913
Name: count, dtype: int64

In [24]:
boolean_cols = [
    "under_pressure",
    "shot_first_time",
    "shot_one_on_one",
    "shot_open_goal",
    "shot_deflected"
]

for col in boolean_cols:
    shots_clean[col] = shots_clean[col].fillna(False)
    shots_clean[col] = shots_clean[col].astype(int)

In [25]:
shots_clean = shots_clean.dropna(
    subset=['x','y']
)

shots_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7863 entries, 0 to 7862
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   match_id           7863 non-null   int64
 1   competition_name   7863 non-null   object
 2   season_name        7863 non-null   int64
 3   minute             7863 non-null   int64
 4   second             7863 non-null   int64
 5   period             7863 non-null   int64
 6   team               7863 non-null   object
 7   player             7863 non-null   object
 8   position           7863 non-null   object
 9   location           7863 non-null   object
 10  shot_end_location  7863 non-null   object
 11  shot_body_part     7863 non-null   object
 12  shot_technique     7863 non-null   object
 13  play_pattern       7863 non-null   object
 14  under_pressure     7863 non-null   int64
 15  shot_first_time    7863 non-null   int64
 16  shot_one_on_one    7863 non-null   int64
 17  shot_open_goal     7863 non-null   int64
 18  shot_deflected     7863 non-null   int64
 19  shot_statsbomb_xg  7863 non-null   float64
 20  shot_outcome       7863 non-null   object
 21  x                  7863 non-null   float64
 22  y                  7863 non-null   float64
 23  end_x              0 non-null      object
 24  end_y              0 non-null      object
 25  goal               7863 non-null   int64
dtypes: float64(3), int64(11), object(12)
memory usage: 1.6+ MB

In [27]:
import ast
shots_clean["shot_end_location"] = shots_clean[
    "shot_end_location"
].apply(
    lambda x: ast.literal_eval(x)
    if pd.notnull(x)
    else None
)

In [28]:
shots_clean["end_x"] = shots_clean[
    "shot_end_location"
].apply(
    lambda loc: loc[0]
    if isinstance(loc, list)
    else None
)

shots_clean["end_y"] = shots_clean[
    "shot_end_location"
].apply(
    lambda loc: loc[1]
    if isinstance(loc, list)
    else None
)

In [29]:
shots_clean[["shot_end_location", "end_x", "end_y"]].head()

    shot_end_location  end_x  end_y
0       [115.6, 48.4]  115.6   48.4
1  [120.0, 46.6, 0.3]  120.0   46.6
2  [120.0, 45.7, 6.7]  120.0   45.7
3  [118.1, 40.2, 1.3]  118.1   40.2
4       [113.6, 34.4]  113.6   34.4

In [30]:
shots_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7863 entries, 0 to 7862
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   match_id           7863 non-null   int64
 1   competition_name   7863 non-null   object
 2   season_name        7863 non-null   int64
 3   minute             7863 non-null   int64
 4   second             7863 non-null   int64
 5   period             7863 non-null   int64
 6   team               7863 non-null   object
 7   player             7863 non-null   object
 8   position           7863 non-null   object
 9   location           7863 non-null   object
 10  shot_end_location  7863 non-null   object
 11  shot_body_part     7863 non-null   object
 12  shot_technique     7863 non-null   object
 13  play_pattern       7863 non-null   object
 14  under_pressure     7863 non-null   int64
 15  shot_first_time    7863 non-null   int64
 16  shot_one_on_one    7863 non-null   int64
 17  shot_open_goal     7863 non-null   int64
 18  shot_deflected     7863 non-null   int64
 19  shot_statsbomb_xg  7863 non-null   float64
 20  shot_outcome       7863 non-null   object
 21  x                  7863 non-null   float64
 22  y                  7863 non-null   float64
 23  end_x              7863 non-null   float64
 24  end_y              7863 non-null   float64
 25  goal               7863 non-null   int64
dtypes: float64(5), int64(11), object(10)
memory usage: 1.6+ MB

In [39]:
shots_clean = shots_clean.drop(
    columns=[
        "location",
        "shot_end_location"
    ]
)
# error because i already dropped the column but accidentally ran the block twice/thrice

KeyError: "['location', 'shot_end_location'] not found in axis"

In [40]:
shots_clean = shots_clean.drop_duplicates()

print(shots_clean.shape)

(7863, 24)

In [41]:
shots_clean.to_csv(
    "../data/processed/cleaned_shots.csv",
    index=False
)

print("Cleaned dataset saved successfully")

Cleaned dataset saved successfully